const flags = [
  {
    name: "afghanistan",
    code: "AF",
    capital: "Kabul",
    region: "Asia",
    flag: "https://restcountries.eu/data/afg.svg",
  },
  {
    name: "åland islands",
    code: "AX",
    capital: "Mariehamn",
    region: "Europe",
    flag: "https://restcountries.eu/data/ala.svg",
  },
  {
    name: "albania",
    code: "AL",
    capital: "Tirana",
    region: "Europe",
    flag: "https://restcountries.eu/data/alb.svg",
  },
  {
    name: "algeria",
    code: "DZ",
    capital: "Algiers",
    region: "Africa",
    flag: "https://restcountries.eu/data/dza.svg",
  },
  {
    name: "american samoa",
    code: "AS",
    capital: "Pago Pago",
    region: "Oceania",
    flag: "https://restcountries.eu/data/asm.svg",
  },
  {
    name: "andorra",
    code: "AD",
    capital: "Andorra la Vella",
    region: "Europe",
    flag: "https://restcountries.eu/data/and.svg",
  },
  {
    name: "angola",
    code: "AO",
    capital: "Luanda",
    region: "Africa",
    flag: "https://restcountries.eu/data/ago.svg",
  },
  {
    name: "anguilla",
    code: "AI",
    capital: "The Valley",
    region: "Americas",
    flag: "https://restcountries.eu/data/aia.svg",
  },
  {
    name: "antarctica",
    code: "AQ",
    capital: "",
    region: "Polar",
    flag: "https://restcountries.eu/data/ata.svg",
  },
  {
    name: "antigua and barbuda",
    code: "AG",
    capital: "Saint Johns",
    region: "Americas",
    flag: "https://restcountries.eu/data/atg.svg",
  },
  {
    name: "argentina",
    code: "AR",
    capital: "Buenos Aires",
    region: "Americas",
    flag: "https://restcountries.eu/data/arg.svg",
  },
  {
    name: "armenia",
    code: "AM",
    capital: "Yerevan",
    region: "Asia",
    flag: "https://restcountries.eu/data/arm.svg",
  },
  {
    name: "aruba",
    code: "AW",
    capital: "Oranjestad",
    region: "Americas",
    flag: "https://restcountries.eu/data/abw.svg",
  },
  {
    name: "australia",
    code: "AU",
    capital: "Canberra",
    region: "Oceania",
    flag: "https://restcountries.eu/data/aus.svg",
  },
  {
    name: "austria",
    code: "AT",
    capital: "Vienna",
    region: "Europe",
    flag: "https://restcountries.eu/data/aut.svg",
  },
  {
    name: "azerbaijan",
    code: "AZ",
    capital: "Baku",
    region: "Asia",
    flag: "https://restcountries.eu/data/aze.svg",
  },
  {
    name: "bahamas",
    code: "BS",
    capital: "Nassau",
    region: "Americas",
    flag: "https://restcountries.eu/data/bhs.svg",
  },
  {
    name: "bahrain",
    code: "BH",
    capital: "Manama",
    region: "Asia",
    flag: "https://restcountries.eu/data/bhr.svg",
  },
  {
    name: "bangladesh",
    code: "BD",
    capital: "Dhaka",
    region: "Asia",
    flag: "https://restcountries.eu/data/bgd.svg",
  },
  {
    name: "barbados",
    code: "BB",
    capital: "Bridgetown",
    region: "Americas",
    flag: "https://restcountries.eu/data/brb.svg",
  },
  {
    name: "belarus",
    code: "BY",
    capital: "Minsk",
    region: "Europe",
    flag: "https://restcountries.eu/data/blr.svg",
  },
  {
    name: "belgium",
    code: "BE",
    capital: "Brussels",
    region: "Europe",
    flag: "https://restcountries.eu/data/bel.svg",
  },
  {
    name: "belize",
    code: "BZ",
    capital: "Belmopan",
    region: "Americas",
    flag: "https://restcountries.eu/data/blz.svg",
  },
  {
    name: "benin",
    code: "BJ",
    capital: "Porto-Novo",
    region: "Africa",
    flag: "https://restcountries.eu/data/ben.svg",
  },
  {
    name: "bermuda",
    code: "BM",
    capital: "Hamilton",
    region: "Americas",
    flag: "https://restcountries.eu/data/bmu.svg",
  },
  {
    name: "bhutan",
    code: "BT",
    capital: "Thimphu",
    region: "Asia",
    flag: "https://restcountries.eu/data/btn.svg",
  },
  {
    name: "bolivia (plurinational state of);",
    code: "BO",
    capital: "Sucre",
    region: "Americas",
    flag: "https://restcountries.eu/data/bol.svg",
  },
  {
    name: "bonaire, sint eustatius and saba",
    code: "BQ",
    capital: "Kralendijk",
    region: "Americas",
    flag: "https://restcountries.eu/data/bes.svg",
  },
  {
    name: "bosnia and herzegovina",
    code: "BA",
    capital: "Sarajevo",
    region: "Europe",
    flag: "https://restcountries.eu/data/bih.svg",
  },
  {
    name: "botswana",
    code: "BW",
    capital: "Gaborone",
    region: "Africa",
    flag: "https://restcountries.eu/data/bwa.svg",
  },
  {
    name: "bouvet island",
    code: "BV",
    capital: "",
    region: "",
    flag: "https://restcountries.eu/data/bvt.svg",
  },
  {
    name: "brazil",
    code: "BR",
    capital: "Brasília",
    region: "Americas",
    flag: "https://restcountries.eu/data/bra.svg",
  },
  {
    name: "british indian ocean territory",
    code: "IO",
    capital: "Diego Garcia",
    region: "Africa",
    flag: "https://restcountries.eu/data/iot.svg",
  },
  {
    name: "united states minor outlying islands",
    code: "UM",
    capital: "",
    region: "Americas",
    flag: "https://restcountries.eu/data/umi.svg",
  },
  {
    name: "virgin islands (british);",
    code: "VG",
    capital: "Road Town",
    region: "Americas",
    flag: "https://restcountries.eu/data/vgb.svg",
  },
  {
    name: "virgin islands (u.s.);",
    code: "VI",
    capital: "Charlotte Amalie",
    region: "Americas",
    flag: "https://restcountries.eu/data/vir.svg",
  },
  {
    name: "brunei darussalam",
    code: "BN",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    flag: "https://restcountries.eu/data/brn.svg",
  },
  {
    name: "bulgaria",
    code: "BG",
    capital: "Sofia",
    region: "Europe",
    flag: "https://restcountries.eu/data/bgr.svg",
  },
  {
    name: "burkina faso",
    code: "BF",
    capital: "Ouagadougou",
    region: "Africa",
    flag: "https://restcountries.eu/data/bfa.svg",
  },
  {
    name: "burundi",
    code: "BI",
    capital: "Bujumbura",
    region: "Africa",
    flag: "https://restcountries.eu/data/bdi.svg",
  },
  {
    name: "cambodia",
    code: "KH",
    capital: "Phnom Penh",
    region: "Asia",
    flag: "https://restcountries.eu/data/khm.svg",
  },
  {
    name: "cameroon",
    code: "CM",
    capital: "Yaoundé",
    region: "Africa",
    flag: "https://restcountries.eu/data/cmr.svg",
  },
  {
    name: "canada",
    code: "CA",
    capital: "Ottawa",
    region: "Americas",
    flag: "https://restcountries.eu/data/can.svg",
  },
  {
    name: "cabo verde",
    code: "CV",
    capital: "Praia",
    region: "Africa",
    flag: "https://restcountries.eu/data/cpv.svg",
  },
  {
    name: "cayman islands",
    code: "KY",
    capital: "George Town",
    region: "Americas",
    flag: "https://restcountries.eu/data/cym.svg",
  },
  {
    name: "central african republic",
    code: "CF",
    capital: "Bangui",
    region: "Africa",
    flag: "https://restcountries.eu/data/caf.svg",
  },
  {
    name: "chad",
    code: "TD",
    capital: "NDjamena",
    region: "Africa",
    flag: "https://restcountries.eu/data/tcd.svg",
  },
  {
    name: "chile",
    code: "CL",
    capital: "Santiago",
    region: "Americas",
    flag: "https://restcountries.eu/data/chl.svg",
  },
  {
    name: "china",
    code: "CN",
    capital: "Beijing",
    region: "Asia",
    flag: "https://restcountries.eu/data/chn.svg",
  },
  {
    name: "christmas island",
    code: "CX",
    capital: "Flying Fish Cove",
    region: "Oceania",
    flag: "https://restcountries.eu/data/cxr.svg",
  },
  {
    name: "cocos islands",
    code: "CC",
    capital: "West Island",
    region: "Oceania",
    flag: "https://restcountries.eu/data/cck.svg",
  },
  {
    name: "colombia",
    code: "CO",
    capital: "Bogotá",
    region: "Americas",
    flag: "https://restcountries.eu/data/col.svg",
  },
  {
    name: "comoros",
    code: "KM",
    capital: "Moroni",
    region: "Africa",
    flag: "https://restcountries.eu/data/com.svg",
  },
  {
    name: "congo",
    code: "CG",
    capital: "Brazzaville",
    region: "Africa",
    flag: "https://restcountries.eu/data/cog.svg",
  },
  {
    name: "congo (democratic republic of the);",
    code: "CD",
    capital: "Kinshasa",
    region: "Africa",
    flag: "https://restcountries.eu/data/cod.svg",
  },
  {
    name: "cook islands",
    code: "CK",
    capital: "Avarua",
    region: "Oceania",
    flag: "https://restcountries.eu/data/cok.svg",
  },
  {
    name: "costa rica",
    code: "CR",
    capital: "San José",
    region: "Americas",
    flag: "https://restcountries.eu/data/cri.svg",
  },
  {
    name: "croatia",
    code: "HR",
    capital: "Zagreb",
    region: "Europe",
    flag: "https://restcountries.eu/data/hrv.svg",
  },
  {
    name: "cuba",
    code: "CU",
    capital: "Havana",
    region: "Americas",
    flag: "https://restcountries.eu/data/cub.svg",
  },
  {
    name: "curaçao",
    code: "CW",
    capital: "Willemstad",
    region: "Americas",
    flag: "https://restcountries.eu/data/cuw.svg",
  },
  {
    name: "cyprus",
    code: "CY",
    capital: "Nicosia",
    region: "Europe",
    flag: "https://restcountries.eu/data/cyp.svg",
  },
  {
    name: "czech republic",
    code: "CZ",
    capital: "Prague",
    region: "Europe",
    flag: "https://restcountries.eu/data/cze.svg",
  },
  {
    name: "denmark",
    code: "DK",
    capital: "Copenhagen",
    region: "Europe",
    flag: "https://restcountries.eu/data/dnk.svg",
  },
  {
    name: "djibouti",
    code: "DJ",
    capital: "Djibouti",
    region: "Africa",
    flag: "https://restcountries.eu/data/dji.svg",
  },
  {
    name: "dominica",
    code: "DM",
    capital: "Roseau",
    region: "Americas",
    flag: "https://restcountries.eu/data/dma.svg",
  },
  {
    name: "dominican republic",
    code: "DO",
    capital: "Santo Domingo",
    region: "Americas",
    flag: "https://restcountries.eu/data/dom.svg",
  },
  {
    name: "ecuador",
    code: "EC",
    capital: "Quito",
    region: "Americas",
    flag: "https://restcountries.eu/data/ecu.svg",
  },
  {
    name: "egypt",
    code: "EG",
    capital: "Cairo",
    region: "Africa",
    flag: "https://restcountries.eu/data/egy.svg",
  },
  {
    name: "el salvador",
    code: "SV",
    capital: "San Salvador",
    region: "Americas",
    flag: "https://restcountries.eu/data/slv.svg",
  },
  {
    name: "equatorial guinea",
    code: "GQ",
    capital: "Malabo",
    region: "Africa",
    flag: "https://restcountries.eu/data/gnq.svg",
  },
  {
    name: "eritrea",
    code: "ER",
    capital: "Asmara",
    region: "Africa",
    flag: "https://restcountries.eu/data/eri.svg",
  },
  {
    name: "estonia",
    code: "EE",
    capital: "Tallinn",
    region: "Europe",
    flag: "https://restcountries.eu/data/est.svg",
  },
  {
    name: "ethiopia",
    code: "ET",
    capital: "Addis Ababa",
    region: "Africa",
    flag: "https://restcountries.eu/data/eth.svg",
  },
  {
    name: "falkland islands (malvinas);",
    code: "FK",
    capital: "Stanley",
    region: "Americas",
    flag: "https://restcountries.eu/data/flk.svg",
  },
  {
    name: "faroe islands",
    code: "FO",
    capital: "Tórshavn",
    region: "Europe",
    flag: "https://restcountries.eu/data/fro.svg",
  },
  {
    name: "fiji",
    code: "FJ",
    capital: "Suva",
    region: "Oceania",
    flag: "https://restcountries.eu/data/fji.svg",
  },
  {
    name: "finland",
    code: "FI",
    capital: "Helsinki",
    region: "Europe",
    flag: "https://restcountries.eu/data/fin.svg",
  },
  {
    name: "france",
    code: "FR",
    capital: "Paris",
    region: "Europe",
    flag: "https://restcountries.eu/data/fra.svg",
  },
  {
    name: "french guiana",
    code: "GF",
    capital: "Cayenne",
    region: "Americas",
    flag: "https://restcountries.eu/data/guf.svg",
  },
  {
    name: "french polynesia",
    code: "PF",
    capital: "Papeetē",
    region: "Oceania",
    flag: "https://restcountries.eu/data/pyf.svg",
  },
  {
    name: "french southern territories",
    code: "TF",
    capital: "Port-aux-Français",
    region: "Africa",
    flag: "https://restcountries.eu/data/atf.svg",
  },
  {
    name: "gabon",
    code: "GA",
    capital: "Libreville",
    region: "Africa",
    flag: "https://restcountries.eu/data/gab.svg",
  },
  {
    name: "gambia",
    code: "GM",
    capital: "Banjul",
    region: "Africa",
    flag: "https://restcountries.eu/data/gmb.svg",
  },
  {
    name: "georgia",
    code: "GE",
    capital: "Tbilisi",
    region: "Asia",
    flag: "https://restcountries.eu/data/geo.svg",
  },
  {
    name: "germany",
    code: "DE",
    capital: "Berlin",
    region: "Europe",
    flag: "https://restcountries.eu/data/deu.svg",
  },
  {
    name: "ghana",
    code: "GH",
    capital: "Accra",
    region: "Africa",
    flag: "https://restcountries.eu/data/gha.svg",
  },
  {
    name: "gibraltar",
    code: "GI",
    capital: "Gibraltar",
    region: "Europe",
    flag: "https://restcountries.eu/data/gib.svg",
  },
  {
    name: "greece",
    code: "GR",
    capital: "Athens",
    region: "Europe",
    flag: "https://restcountries.eu/data/grc.svg",
  },
  {
    name: "greenland",
    code: "GL",
    capital: "Nuuk",
    region: "Americas",
    flag: "https://restcountries.eu/data/grl.svg",
  },
  {
    name: "grenada",
    code: "GD",
    capital: "St. Georges",
    region: "Americas",
    flag: "https://restcountries.eu/data/grd.svg",
  },
  {
    name: "guadeloupe",
    code: "GP",
    capital: "Basse-Terre",
    region: "Americas",
    flag: "https://restcountries.eu/data/glp.svg",
  },
  {
    name: "guam",
    code: "GU",
    capital: "Hagåtña",
    region: "Oceania",
    flag: "https://restcountries.eu/data/gum.svg",
  },
  {
    name: "guatemala",
    code: "GT",
    capital: "Guatemala City",
    region: "Americas",
    flag: "https://restcountries.eu/data/gtm.svg",
  },
  {
    name: "guernsey",
    code: "GG",
    capital: "St. Peter Port",
    region: "Europe",
    flag: "https://restcountries.eu/data/ggy.svg",
  },
  {
    name: "guinea",
    code: "GN",
    capital: "Conakry",
    region: "Africa",
    flag: "https://restcountries.eu/data/gin.svg",
  },
  {
    name: "guinea-bissau",
    code: "GW",
    capital: "Bissau",
    region: "Africa",
    flag: "https://restcountries.eu/data/gnb.svg",
  },
  {
    name: "guyana",
    code: "GY",
    capital: "Georgetown",
    region: "Americas",
    flag: "https://restcountries.eu/data/guy.svg",
  },
  {
    name: "haiti",
    code: "HT",
    capital: "Port-au-Prince",
    region: "Americas",
    flag: "https://restcountries.eu/data/hti.svg",
  },
  {
    name: "heard island and mcdonald islands",
    code: "HM",
    capital: "",
    region: "",
    flag: "https://restcountries.eu/data/hmd.svg",
  },
  {
    name: "holy see",
    code: "VA",
    capital: "Rome",
    region: "Europe",
    flag: "https://restcountries.eu/data/vat.svg",
  },
  {
    name: "honduras",
    code: "HN",
    capital: "Tegucigalpa",
    region: "Americas",
    flag: "https://restcountries.eu/data/hnd.svg",
  },
  {
    name: "hong kong",
    code: "HK",
    capital: "City of Victoria",
    region: "Asia",
    flag: "https://restcountries.eu/data/hkg.svg",
  },
  {
    name: "hungary",
    code: "HU",
    capital: "Budapest",
    region: "Europe",
    flag: "https://restcountries.eu/data/hun.svg",
  },
  {
    name: "iceland",
    code: "IS",
    capital: "Reykjavík",
    region: "Europe",
    flag: "https://restcountries.eu/data/isl.svg",
  },
  {
    name: "india",
    code: "IN",
    capital: "New Delhi",
    region: "Asia",
    flag: "https://restcountries.eu/data/ind.svg",
  },
  {
    name: "indonesia",
    code: "ID",
    capital: "Jakarta",
    region: "Asia",
    flag: "https://restcountries.eu/data/idn.svg",
  },
  {
    name: "côte divoire",
    code: "CI",
    capital: "Yamoussoukro",
    region: "Africa",
    flag: "https://restcountries.eu/data/civ.svg",
  },
  {
    name: "iran",
    code: "IR",
    capital: "Tehran",
    region: "Asia",
    flag: "https://restcountries.eu/data/irn.svg",
  },
  {
    name: "iraq",
    code: "IQ",
    capital: "Baghdad",
    region: "Asia",
    flag: "https://restcountries.eu/data/irq.svg",
  },
  {
    name: "ireland",
    code: "IE",
    capital: "Dublin",
    region: "Europe",
    flag: "https://restcountries.eu/data/irl.svg",
  },
  {
    name: "isle of man",
    code: "IM",
    capital: "Douglas",
    region: "Europe",
    flag: "https://restcountries.eu/data/imn.svg",
  },
  {
    name: "israel",
    code: "IL",
    capital: "Jerusalem",
    region: "Asia",
    flag: "https://restcountries.eu/data/isr.svg",
  },
  {
    name: "italy",
    code: "IT",
    capital: "Rome",
    region: "Europe",
    flag: "https://restcountries.eu/data/ita.svg",
  },
  {
    name: "jamaica",
    code: "JM",
    capital: "Kingston",
    region: "Americas",
    flag: "https://restcountries.eu/data/jam.svg",
  },
  {
    name: "japan",
    code: "JP",
    capital: "Tokyo",
    region: "Asia",
    flag: "https://restcountries.eu/data/jpn.svg",
  },
  {
    name: "jersey",
    code: "JE",
    capital: "Saint Helier",
    region: "Europe",
    flag: "https://restcountries.eu/data/jey.svg",
  },
  {
    name: "jordan",
    code: "JO",
    capital: "Amman",
    region: "Asia",
    flag: "https://restcountries.eu/data/jor.svg",
  },
  {
    name: "kazakhstan",
    code: "KZ",
    capital: "Astana",
    region: "Asia",
    flag: "https://restcountries.eu/data/kaz.svg",
  },
  {
    name: "kenya",
    code: "KE",
    capital: "Nairobi",
    region: "Africa",
    flag: "https://restcountries.eu/data/ken.svg",
  },
  {
    name: "kiribati",
    code: "KI",
    capital: "South Tarawa",
    region: "Oceania",
    flag: "https://restcountries.eu/data/kir.svg",
  },
  {
    name: "kuwait",
    code: "KW",
    capital: "Kuwait City",
    region: "Asia",
    flag: "https://restcountries.eu/data/kwt.svg",
  },
  {
    name: "kyrgyzstan",
    code: "KG",
    capital: "Bishkek",
    region: "Asia",
    flag: "https://restcountries.eu/data/kgz.svg",
  },
  {
    name: "lao peoples democratic republic",
    code: "LA",
    capital: "Vientiane",
    region: "Asia",
    flag: "https://restcountries.eu/data/lao.svg",
  },
  {
    name: "latvia",
    code: "LV",
    capital: "Riga",
    region: "Europe",
    flag: "https://restcountries.eu/data/lva.svg",
  },
  {
    name: "lebanon",
    code: "LB",
    capital: "Beirut",
    region: "Asia",
    flag: "https://restcountries.eu/data/lbn.svg",
  },
  {
    name: "lesotho",
    code: "LS",
    capital: "Maseru",
    region: "Africa",
    flag: "https://restcountries.eu/data/lso.svg",
  },
  {
    name: "liberia",
    code: "LR",
    capital: "Monrovia",
    region: "Africa",
    flag: "https://restcountries.eu/data/lbr.svg",
  },
  {
    name: "libya",
    code: "LY",
    capital: "Tripoli",
    region: "Africa",
    flag: "https://restcountries.eu/data/lby.svg",
  },
  {
    name: "liechtenstein",
    code: "LI",
    capital: "Vaduz",
    region: "Europe",
    flag: "https://restcountries.eu/data/lie.svg",
  },
  {
    name: "lithuania",
    code: "LT",
    capital: "Vilnius",
    region: "Europe",
    flag: "https://restcountries.eu/data/ltu.svg",
  },
  {
    name: "luxembourg",
    code: "LU",
    capital: "Luxembourg",
    region: "Europe",
    flag: "https://restcountries.eu/data/lux.svg",
  },
  {
    name: "macao",
    code: "MO",
    capital: "",
    region: "Asia",
    flag: "https://restcountries.eu/data/mac.svg",
  },
  {
    name: "macedonia (the former yugoslav republic of);",
    code: "MK",
    capital: "Skopje",
    region: "Europe",
    flag: "https://restcountries.eu/data/mkd.svg",
  },
  {
    name: "madagascar",
    code: "MG",
    capital: "Antananarivo",
    region: "Africa",
    flag: "https://restcountries.eu/data/mdg.svg",
  },
  {
    name: "malawi",
    code: "MW",
    capital: "Lilongwe",
    region: "Africa",
    flag: "https://restcountries.eu/data/mwi.svg",
  },
  {
    name: "malaysia",
    code: "MY",
    capital: "Kuala Lumpur",
    region: "Asia",
    flag: "https://restcountries.eu/data/mys.svg",
  },
  {
    name: "maldives",
    code: "MV",
    capital: "Malé",
    region: "Asia",
    flag: "https://restcountries.eu/data/mdv.svg",
  },
  {
    name: "mali",
    code: "ML",
    capital: "Bamako",
    region: "Africa",
    flag: "https://restcountries.eu/data/mli.svg",
  },
  {
    name: "malta",
    code: "MT",
    capital: "Valletta",
    region: "Europe",
    flag: "https://restcountries.eu/data/mlt.svg",
  },
  {
    name: "marshall islands",
    code: "MH",
    capital: "Majuro",
    region: "Oceania",
    flag: "https://restcountries.eu/data/mhl.svg",
  },
  {
    name: "martinique",
    code: "MQ",
    capital: "Fort-de-France",
    region: "Americas",
    flag: "https://restcountries.eu/data/mtq.svg",
  },
  {
    name: "mauritania",
    code: "MR",
    capital: "Nouakchott",
    region: "Africa",
    flag: "https://restcountries.eu/data/mrt.svg",
  },
  {
    name: "mauritius",
    code: "MU",
    capital: "Port Louis",
    region: "Africa",
    flag: "https://restcountries.eu/data/mus.svg",
  },
  {
    name: "mayotte",
    code: "YT",
    capital: "Mamoudzou",
    region: "Africa",
    flag: "https://restcountries.eu/data/myt.svg",
  },
  {
    name: "mexico",
    code: "MX",
    capital: "Mexico City",
    region: "Americas",
    flag: "https://restcountries.eu/data/mex.svg",
  },
  {
    name: "micronesia",
    code: "FM",
    capital: "Palikir",
    region: "Oceania",
    flag: "https://restcountries.eu/data/fsm.svg",
  },
  {
    name: "moldova",
    code: "MD",
    capital: "Chișinău",
    region: "Europe",
    flag: "https://restcountries.eu/data/mda.svg",
  },
  {
    name: "monaco",
    code: "MC",
    capital: "Monaco",
    region: "Europe",
    flag: "https://restcountries.eu/data/mco.svg",
  },
  {
    name: "mongolia",
    code: "MN",
    capital: "Ulan Bator",
    region: "Asia",
    flag: "https://restcountries.eu/data/mng.svg",
  },
  {
    name: "montenegro",
    code: "ME",
    capital: "Podgorica",
    region: "Europe",
    flag: "https://restcountries.eu/data/mne.svg",
  },
  {
    name: "montserrat",
    code: "MS",
    capital: "Plymouth",
    region: "Americas",
    flag: "https://restcountries.eu/data/msr.svg",
  },
  {
    name: "morocco",
    code: "MA",
    capital: "Rabat",
    region: "Africa",
    flag: "https://restcountries.eu/data/mar.svg",
  },
  {
    name: "mozambique",
    code: "MZ",
    capital: "Maputo",
    region: "Africa",
    flag: "https://restcountries.eu/data/moz.svg",
  },
  {
    name: "myanmar",
    code: "MM",
    capital: "Naypyidaw",
    region: "Asia",
    flag: "https://restcountries.eu/data/mmr.svg",
  },
  {
    name: "namibia",
    code: "NA",
    capital: "Windhoek",
    region: "Africa",
    flag: "https://restcountries.eu/data/nam.svg",
  },
  {
    name: "nauru",
    code: "NR",
    capital: "Yaren",
    region: "Oceania",
    flag: "https://restcountries.eu/data/nru.svg",
  },
  {
    name: "nepal",
    code: "NP",
    capital: "Kathmandu",
    region: "Asia",
    flag: "https://restcountries.eu/data/npl.svg",
  },
  {
    name: "netherlands",
    code: "NL",
    capital: "Amsterdam",
    region: "Europe",
    flag: "https://restcountries.eu/data/nld.svg",
  },
  {
    name: "new caledonia",
    code: "NC",
    capital: "Nouméa",
    region: "Oceania",
    flag: "https://restcountries.eu/data/ncl.svg",
  },
  {
    name: "new zealand",
    code: "NZ",
    capital: "Wellington",
    region: "Oceania",
    flag: "https://restcountries.eu/data/nzl.svg",
  },
  {
    name: "nicaragua",
    code: "NI",
    capital: "Managua",
    region: "Americas",
    flag: "https://restcountries.eu/data/nic.svg",
  },
  {
    name: "niger",
    code: "NE",
    capital: "Niamey",
    region: "Africa",
    flag: "https://restcountries.eu/data/ner.svg",
  },
  {
    name: "nigeria",
    code: "NG",
    capital: "Abuja",
    region: "Africa",
    flag: "https://restcountries.eu/data/nga.svg",
  },
  {
    name: "niue",
    code: "NU",
    capital: "Alofi",
    region: "Oceania",
    flag: "https://restcountries.eu/data/niu.svg",
  },
  {
    name: "norfolk island",
    code: "NF",
    capital: "Kingston",
    region: "Oceania",
    flag: "https://restcountries.eu/data/nfk.svg",
  },
  {
    name: "korea (democratic peoples republic of);",
    code: "KP",
    capital: "Pyongyang",
    region: "Asia",
    flag: "https://restcountries.eu/data/prk.svg",
  },
  {
    name: "northern mariana islands",
    code: "MP",
    capital: "Saipan",
    region: "Oceania",
    flag: "https://restcountries.eu/data/mnp.svg",
  },
  {
    name: "norway",
    code: "NO",
    capital: "Oslo",
    region: "Europe",
    flag: "https://restcountries.eu/data/nor.svg",
  },
  {
    name: "oman",
    code: "OM",
    capital: "Muscat",
    region: "Asia",
    flag: "https://restcountries.eu/data/omn.svg",
  },
  {
    name: "pakistan",
    code: "PK",
    capital: "Islamabad",
    region: "Asia",
    flag: "https://restcountries.eu/data/pak.svg",
  },
  {
    name: "palau",
    code: "PW",
    capital: "Ngerulmud",
    region: "Oceania",
    flag: "https://restcountries.eu/data/plw.svg",
  },
  {
    name: "palestine, state of",
    code: "PS",
    capital: "Ramallah",
    region: "Asia",
    flag: "https://restcountries.eu/data/pse.svg",
  },
  {
    name: "panama",
    code: "PA",
    capital: "Panama City",
    region: "Americas",
    flag: "https://restcountries.eu/data/pan.svg",
  },
  {
    name: "papua new guinea",
    code: "PG",
    capital: "Port Moresby",
    region: "Oceania",
    flag: "https://restcountries.eu/data/png.svg",
  },
  {
    name: "paraguay",
    code: "PY",
    capital: "Asunción",
    region: "Americas",
    flag: "https://restcountries.eu/data/pry.svg",
  },
  {
    name: "peru",
    code: "PE",
    capital: "Lima",
    region: "Americas",
    flag: "https://restcountries.eu/data/per.svg",
  },
  {
    name: "philippines",
    code: "PH",
    capital: "Manila",
    region: "Asia",
    flag: "https://restcountries.eu/data/phl.svg",
  },
  {
    name: "pitcairn",
    code: "PN",
    capital: "Adamstown",
    region: "Oceania",
    flag: "https://restcountries.eu/data/pcn.svg",
  },
  {
    name: "poland",
    code: "PL",
    capital: "Warsaw",
    region: "Europe",
    flag: "https://restcountries.eu/data/pol.svg",
  },
  {
    name: "portugal",
    code: "PT",
    capital: "Lisbon",
    region: "Europe",
    flag: "https://restcountries.eu/data/prt.svg",
  },
  {
    name: "puerto rico",
    code: "PR",
    capital: "San Juan",
    region: "Americas",
    flag: "https://restcountries.eu/data/pri.svg",
  },
  {
    name: "qatar",
    code: "QA",
    capital: "Doha",
    region: "Asia",
    flag: "https://restcountries.eu/data/qat.svg",
  },
  {
    name: "republic of kosovo",
    code: "XK",
    capital: "Pristina",
    region: "Europe",
    flag: "https://restcountries.eu/data/kos.svg",
  },
  {
    name: "réunion",
    code: "RE",
    capital: "Saint-Denis",
    region: "Africa",
    flag: "https://restcountries.eu/data/reu.svg",
  },
  {
    name: "romania",
    code: "RO",
    capital: "Bucharest",
    region: "Europe",
    flag: "https://restcountries.eu/data/rou.svg",
  },
  {
    name: "russian federation",
    code: "RU",
    capital: "Moscow",
    region: "Europe",
    flag: "https://restcountries.eu/data/rus.svg",
  },
  {
    name: "rwanda",
    code: "RW",
    capital: "Kigali",
    region: "Africa",
    flag: "https://restcountries.eu/data/rwa.svg",
  },
  {
    name: "saint barthélemy",
    code: "BL",
    capital: "Gustavia",
    region: "Americas",
    flag: "https://restcountries.eu/data/blm.svg",
  },
  {
    name: "saint helena, ascension and tristan da cunha",
    code: "SH",
    capital: "Jamestown",
    region: "Africa",
    flag: "https://restcountries.eu/data/shn.svg",
  },
  {
    name: "saint kitts and nevis",
    code: "KN",
    capital: "Basseterre",
    region: "Americas",
    flag: "https://restcountries.eu/data/kna.svg",
  },
  {
    name: "saint lucia",
    code: "LC",
    capital: "Castries",
    region: "Americas",
    flag: "https://restcountries.eu/data/lca.svg",
  },
  {
    name: "saint martin (french part);",
    code: "MF",
    capital: "Marigot",
    region: "Americas",
    flag: "https://restcountries.eu/data/maf.svg",
  },
  {
    name: "saint pierre and miquelon",
    code: "PM",
    capital: "Saint-Pierre",
    region: "Americas",
    flag: "https://restcountries.eu/data/spm.svg",
  },
  {
    name: "saint vincent and the grenadines",
    code: "VC",
    capital: "Kingstown",
    region: "Americas",
    flag: "https://restcountries.eu/data/vct.svg",
  },
  {
    name: "samoa",
    code: "WS",
    capital: "Apia",
    region: "Oceania",
    flag: "https://restcountries.eu/data/wsm.svg",
  },
  {
    name: "san marino",
    code: "SM",
    capital: "City of San Marino",
    region: "Europe",
    flag: "https://restcountries.eu/data/smr.svg",
  },
  {
    name: "sao tome and principe",
    code: "ST",
    capital: "São Tomé",
    region: "Africa",
    flag: "https://restcountries.eu/data/stp.svg",
  },
  {
    name: "saudi arabia",
    code: "SA",
    capital: "Riyadh",
    region: "Asia",
    flag: "https://restcountries.eu/data/sau.svg",
  },
  {
    name: "senegal",
    code: "SN",
    capital: "Dakar",
    region: "Africa",
    flag: "https://restcountries.eu/data/sen.svg",
  },
  {
    name: "serbia",
    code: "RS",
    capital: "Belgrade",
    region: "Europe",
    flag: "https://restcountries.eu/data/srb.svg",
  },
  {
    name: "seychelles",
    code: "SC",
    capital: "Victoria",
    region: "Africa",
    flag: "https://restcountries.eu/data/syc.svg",
  },
  {
    name: "sierra leone",
    code: "SL",
    capital: "Freetown",
    region: "Africa",
    flag: "https://restcountries.eu/data/sle.svg",
  },
  {
    name: "singapore",
    code: "SG",
    capital: "Singapore",
    region: "Asia",
    flag: "https://restcountries.eu/data/sgp.svg",
  },
  {
    name: "sint maarten (dutch part);",
    code: "SX",
    capital: "Philipsburg",
    region: "Americas",
    flag: "https://restcountries.eu/data/sxm.svg",
  },
  {
    name: "slovakia",
    code: "SK",
    capital: "Bratislava",
    region: "Europe",
    flag: "https://restcountries.eu/data/svk.svg",
  },
  {
    name: "slovenia",
    code: "SI",
    capital: "Ljubljana",
    region: "Europe",
    flag: "https://restcountries.eu/data/svn.svg",
  },
  {
    name: "solomon islands",
    code: "SB",
    capital: "Honiara",
    region: "Oceania",
    flag: "https://restcountries.eu/data/slb.svg",
  },
  {
    name: "somalia",
    code: "SO",
    capital: "Mogadishu",
    region: "Africa",
    flag: "https://restcountries.eu/data/som.svg",
  },
  {
    name: "south africa",
    code: "ZA",
    capital: "Pretoria",
    region: "Africa",
    flag: "https://restcountries.eu/data/zaf.svg",
  },
  {
    name: "south georgia and the south sandwich islands",
    code: "GS",
    capital: "King Edward Point",
    region: "Americas",
    flag: "https://restcountries.eu/data/sgs.svg",
  },
  {
    name: "korea",
    code: "KR",
    capital: "Seoul",
    region: "Asia",
    flag: "https://restcountries.eu/data/kor.svg",
  },
  {
    name: "south sudan",
    code: "SS",
    capital: "Juba",
    region: "Africa",
    flag: "https://restcountries.eu/data/ssd.svg",
  },
  {
    name: "spain",
    code: "ES",
    capital: "Madrid",
    region: "Europe",
    flag: "https://restcountries.eu/data/esp.svg",
  },
  {
    name: "sri lanka",
    code: "LK",
    capital: "Colombo",
    region: "Asia",
    flag: "https://restcountries.eu/data/lka.svg",
  },
  {
    name: "sudan",
    code: "SD",
    capital: "Khartoum",
    region: "Africa",
    flag: "https://restcountries.eu/data/sdn.svg",
  },
  {
    name: "suriname",
    code: "SR",
    capital: "Paramaribo",
    region: "Americas",
    flag: "https://restcountries.eu/data/sur.svg",
  },
  {
    name: "svalbard and jan mayen",
    code: "SJ",
    capital: "Longyearbyen",
    region: "Europe",
    flag: "https://restcountries.eu/data/sjm.svg",
  },
  {
    name: "swaziland",
    code: "SZ",
    capital: "Lobamba",
    region: "Africa",
    flag: "https://restcountries.eu/data/swz.svg",
  },
  {
    name: "sweden",
    code: "SE",
    capital: "Stockholm",
    region: "Europe",
    flag: "https://restcountries.eu/data/swe.svg",
  },
  {
    name: "switzerland",
    code: "CH",
    capital: "Bern",
    region: "Europe",
    flag: "https://restcountries.eu/data/che.svg",
  },
  {
    name: "syrian arab republic",
    code: "SY",
    capital: "Damascus",
    region: "Asia",
    flag: "https://restcountries.eu/data/syr.svg",
  },
  {
    name: "taiwan",
    code: "TW",
    capital: "Taipei",
    region: "Asia",
    flag: "https://restcountries.eu/data/twn.svg",
  },
  {
    name: "tajikistan",
    code: "TJ",
    capital: "Dushanbe",
    region: "Asia",
    flag: "https://restcountries.eu/data/tjk.svg",
  },
  {
    name: "tanzania, united republic of",
    code: "TZ",
    capital: "Dodoma",
    region: "Africa",
    flag: "https://restcountries.eu/data/tza.svg",
  },
  {
    name: "thailand",
    code: "TH",
    capital: "Bangkok",
    region: "Asia",
    flag: "https://restcountries.eu/data/tha.svg",
  },
  {
    name: "timor-leste",
    code: "TL",
    capital: "Dili",
    region: "Asia",
    flag: "https://restcountries.eu/data/tls.svg",
  },
  {
    name: "togo",
    code: "TG",
    capital: "Lomé",
    region: "Africa",
    flag: "https://restcountries.eu/data/tgo.svg",
  },
  {
    name: "tokelau",
    code: "TK",
    capital: "Fakaofo",
    region: "Oceania",
    flag: "https://restcountries.eu/data/tkl.svg",
  },
  {
    name: "tonga",
    code: "TO",
    capital: "Nukualofa",
    region: "Oceania",
    flag: "https://restcountries.eu/data/ton.svg",
  },
  {
    name: "trinidad and tobago",
    code: "TT",
    capital: "Port of Spain",
    region: "Americas",
    flag: "https://restcountries.eu/data/tto.svg",
  },
  {
    name: "tunisia",
    code: "TN",
    capital: "Tunis",
    region: "Africa",
    flag: "https://restcountries.eu/data/tun.svg",
  },
  {
    name: "turkey",
    code: "TR",
    capital: "Ankara",
    region: "Asia",
    flag: "https://restcountries.eu/data/tur.svg",
  },
  {
    name: "turkmenistan",
    code: "TM",
    capital: "Ashgabat",
    region: "Asia",
    flag: "https://restcountries.eu/data/tkm.svg",
  },
  {
    name: "turks and caicos islands",
    code: "TC",
    capital: "Cockburn Town",
    region: "Americas",
    flag: "https://restcountries.eu/data/tca.svg",
  },
  {
    name: "tuvalu",
    code: "TV",
    capital: "Funafuti",
    region: "Oceania",
    flag: "https://restcountries.eu/data/tuv.svg",
  },
  {
    name: "uganda",
    code: "UG",
    capital: "Kampala",
    region: "Africa",
    flag: "https://restcountries.eu/data/uga.svg",
  },
  {
    name: "ukraine",
    code: "UA",
    capital: "Kiev",
    region: "Europe",
    flag: "https://restcountries.eu/data/ukr.svg",
  },
  {
    name: "united arab emirates",
    code: "AE",
    capital: "Abu Dhabi",
    region: "Asia",
    flag: "https://restcountries.eu/data/are.svg",
  },
  {
    name: "united kingdom of great britain and northern ireland",
    code: "GB",
    capital: "London",
    region: "Europe",
    flag: "https://restcountries.eu/data/gbr.svg",
  },
  {
    name: "united states of america",
    code: "US",
    capital: "Washington, D.C.",
    region: "Americas",
    flag: "https://restcountries.eu/data/usa.svg",
  },
  {
    name: "uruguay",
    code: "UY",
    capital: "Montevideo",
    region: "Americas",
    flag: "https://restcountries.eu/data/ury.svg",
  },
  {
    name: "uzbekistan",
    code: "UZ",
    capital: "Tashkent",
    region: "Asia",
    flag: "https://restcountries.eu/data/uzb.svg",
  },
  {
    name: "vanuatu",
    code: "VU",
    capital: "Port Vila",
    region: "Oceania",
    flag: "https://restcountries.eu/data/vut.svg",
  },
  {
    name: "venezuela",
    code: "VE",
    capital: "Caracas",
    region: "Americas",
    flag: "https://restcountries.eu/data/ven.svg",
  },
  {
    name: "viet nam",
    code: "VN",
    capital: "Hanoi",
    region: "Asia",
    flag: "https://restcountries.eu/data/vnm.svg",
  },
  {
    name: "wallis and futuna",
    code: "WF",
    capital: "Mata-Utu",
    region: "Oceania",
    flag: "https://restcountries.eu/data/wlf.svg",
  },
  {
    name: "western sahara",
    code: "EH",
    capital: "El Aaiún",
    region: "Africa",
    flag: "https://restcountries.eu/data/esh.svg",
  },
  {
    name: "yemen",
    code: "YE",
    capital: "Sanaa",
    region: "Asia",
    flag: "https://restcountries.eu/data/yem.svg",
  },
  {
    name: "zambia",
    code: "ZM",
    capital: "Lusaka",
    region: "Africa",
    flag: "https://restcountries.eu/data/zmb.svg",
  },
  {
    name: "zimbabwe",
    code: "ZW",
    capital: "Harare",
    region: "Africa",
    flag: "https://restcountries.eu/data/zwe.svg",
  },
];

export { flags };
